spring.application.name=GymManagementSystem

# Konfiguracja bazy danych H2 (In-memory)
spring.datasource.url=jdbc:h2:mem:gymdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Konsola H2 - dostepna pod /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Automatyczne tworzenie schematu bazy danych na podstawie encji
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Dokumentacja Swagger (opcjonalna konfiguracja sciezki)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html